version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: fd-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: fd-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://fd-kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  redis:
    image: redis:7
    container_name: fd-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: fd-postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  order:
    build:
      context: .
      dockerfile: services/order/Dockerfile
    container_name: fd-order
    env_file:
      - .env
    ports:
      - "8081:8081"

  restaurant:
    build:
      context: .
      dockerfile: services/restaurant/Dockerfile
    container_name: fd-restaurant
    env_file:
      - .env
    ports:
      - "8080:8080"

  delivery:
    build:
      context: .
      dockerfile: services/delivery/Dockerfile
    container_name: fd-delivery
    env_file:
      - .env

  # rating:
  #   build:
  #     context: ./services/rating
  #     dockerfile: Dockerfile
  #   container_name: fd-rating
  #   env_file:
  #     - .env
  #   depends_on:
  #     - kafka
  #     - redis
  #   ports:
  #     - "8084:8080"

volumes:
  pgdata:
